var a= 3;
x = 2;
height:30px;
        width: 130px;
        color: #fff;
        background-color: rgba(78, 197, 63, 0.753);
        position: relative;
        position: absolute;
        top: 50px;
        left: 20px;
